---
title: "Analysis of the impacts of storms and weather events on the American economy"
author: "Francisco Lima Figueiredo"
date: "april 17, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Synopsis

Severe climatic events can affect the health and economy of a country or population. We will identify the most damaging events in relation to population health and those with the greatest economic consequences in the USA. This analysis is based on historical data on severe weather events in the United States from 1950 to 2011, which are available from the National Oceanic and Atmospheric Administration (NOAA). These data show the number of fatalities and injuries in each event, as well as the economic damage to plantations and properties. We consider here the total effect of each type of event over the years. We observed that tornados ended up being the event that most affected human health, while floods is the event linked to the greatest economic damage.


## Obtaining and processing available raw data

The following available information is available:

* Raw data: (https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2);
* Documentation: (https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2Fpd01016005curr.pdf);
* Frequently Asked Questions: (https://d396qusza40orc.cloudfront.net/repdata%2Fpeer2_doc%2FNCDC%20Storm%20Events-FAQ%20Page.pdf);

The events described in the database begin in the year 1950 and end in November 2011. In the early years of the database, there are usually fewer events logged, probably due to lack of good records. In more recent years they should be considered more complete.

```r
# load necessary packages
if("data.table" %in% rownames(installed.packages()) == FALSE) {install.packages("data.table")}; library(data.table);
if("lubridate" %in% rownames(installed.packages()) == FALSE) {install.packages("lubridate")}; library(lubridate);

# download and descompress data
if(!dir.exists('data')){dir.create('data')}
compress_file <- 'data/data.csv.bz2';
download.file("https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2",compress_file)
bunzip2 ("data.csv.bz2", overwrite=TRUE, remove=FALSE, destname="data/data-storm.csv") 
unlink(compress_file)

# read original csv data in R environment
original_data <- fread("data/data-storm.csv")
```
